[package]
name = "chip8_emulator"
version = "0.1.0"
authors = ["vancha"]
edition = "2024"

[dependencies]
chippie-gui = { path = "./crates/chippie-gui", version = "0.1.0" }

[features]
x11 = ["chippie-gui/x11"]
wayland = ["chippie-gui/wayland"]
default = ["wayland"]

[workspace]
members = [
    "crates/*",
]
default-members = [
    ".",
    "crates/*",
]

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = 3
strip = "symbols"
incremental = true
