[package]
name = "chippie"
version = "0.1.0"
authors = ["vancha"]
edition = "2024"

[dependencies]
chippie-gui = { path = "./crates/chippie-gui", version = "0.1.0", optional = true }

[features]
x11 = ["dep:chippie-gui", "chippie-gui/x11"]
wayland = ["dep:chippie-gui", "chippie-gui/wayland"]
default = ["wayland"]

[workspace]
members = [
    ".",
    "crates/*",
]

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = 3
strip = "symbols"
incremental = true
